services:
  qbittorrent:
    image: 'lscr.io/linuxserver/qbittorrent:latest'
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6882
    volumes:
      - '/home/marcelo/docker/qbittorrent/config:/config'
      - '/home/marcelo/Downloads:/downloads'
    ports:
      - '8081:8081'
      - '6882:6882'
      - '6882:6882/udp'
    restart: unless-stopped
