version: "3"
services:
   appsmith:
     image: index.docker.io/appsmith/appsmith-ce
     container_name: appsmith
     ports:
         - "85:80"
         - "7443:443"
     volumes:
         - ./stacks:/appsmith-stacks
     restart: unless-stopped
