version: '3.8'
services:
  logseq:
    image: 'ghcr.io/logseq/logseq-webapp:latest'
    container_name: logseq
    restart: unless-stopped
    ports:
      - '3010:80'
    environment:
      NODE_ENV: production
    volumes:
      - 'logseq_data:/data'
volumes:
  logseq_data: null
