services:
  radarr:
    image: 'lscr.io/linuxserver/radarr:latest'
    container_name: radarr
    ports:
      - '7878:7878'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - '/home/marcelo/docker/radarr/config:/config'
      - '/home/marcelo/Downloads:/downloads'
      - '/home/marcelo/media/movies:/movies'
    restart: unless-stopped
